version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: owlculus_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: H1ng3isgro$$
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      POSTGRES_DB: owlculus_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: H1ng3isgro$$
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: thisisthesecret
      FRONTEND_URL: http://localhost:5174
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5174:5174"
    environment:
      ROLLUP_USE_NODE_BUILTINS: true
    platform: linux/amd64
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgdata: